### PR TITLE
Fix hp bar not follow predator problem and add config value to allow adjustment of lerp/smoothing

### PR DESCRIPTION
**Pull request by LostSoul6Years**
as the title implies
fixed this issue:https://github.com/Taureon/aps-plus-plus/issues/7
but retained smoothing (you can choose to turn it off in the config)

### CODE REVIEW

**Comment by LostSoul6Years** [comment]
accept my pull request man

**Comment by Taureon** [comment]
"accept my pull request man"
with this?
image

**Comment by LostSoul6Years** [comment]
> "accept my pull request man" with this? image

whatever man, the first commit was useless, the second commit is what does thing
i wont force you to accept but please acknowledge my effort for fixing predator glitch

**Comment by LostSoul6Years** [comment]
close it maybe

**Comment by 0Richardson2023** [comment]
man wat

**Comment by LostSoul6Years** [comment]
> "accept my pull request man" with this? image

my advice is that you actually read the code. There are two commits. One is the original one and one is new.
maybe you dont care about my effort but that's one hell of a response. Good luck with your project.

**Pull request closed without merging**
