### PR TITLE
Make dreads v2 enabled by default

### PR DESCRIPTION
**Pull request by hussainabidi1**

### CODE REVIEW

**Comment by Trioplane** [comment]
no

**Comment by hussainabidi1** [comment]
why

**Comment by Trioplane** [comment]
bloat, long load times, user can just uncomment it if they want it only takes 10 seconds

**Comment by hussainabidi1** [comment]
waiting for further comment

**Comment by hussainabidi1** [comment]
cuz its part of the game

**Comment by Frostbyte178** [comment]
it takes a couple seconds to load, you can enable it when you want it very easily
will be more like a dozen or more seconds when hexdreads are implemented

**Comment by hussainabidi1** [comment]
hmm
ig if nexus is added then

**Pull request closed without merging**
