### PR TITLE
Some changes

### PR DESCRIPTION
**Pull request by zyrafaq**
Its just for addon devs that want their addon dont crash when another addon doesnt exist

### CODE REVIEW

**Comment by Taureon** [comment]
if this didnt keep the .js from the file name, i would merge

**Comment by zyrafaq** [comment]
@Taureon i updated it! please accept my PR.

**Comment by Taureon** [comment]
image
this is not going to work

**Comment by zyrafaq** [comment]
Why it does cloudflare adds this header

**Comment by Taureon** [comment]
and it also accidentally removes the fastly-client-ip header

**Comment by zyrafaq** [comment]
If i move the "cf-connecting-ip" later just before the req.connection.remoteAddress would it be ok?

**Comment by ClashTest311** [comment]
Accepted with some edits to original request

**Pull request merged**
