### PR TITLE
Entity don't die when collides with wall type fix

### PR DESCRIPTION
**Pull request by GDenisC**
finally

### CODE REVIEW

**Comment by sussyforwut** [comment]
i believe that its related to the assembler

**Comment by Taureon** [comment]
that bug is way older than the assembler ever was

**Comment by sussyforwut** [comment]
oh

**Comment by sussyforwut** [comment]
maybe check the colision system? i barely know anything about this, but it works with traps too

**Comment by sussyforwut** [comment]
i once made a tank extremely bulky, then i ran into a nest keeper trap. i ended up getting trapped there and the traps never died

**Comment by sussyforwut** [comment]
warden*

**Pull request merged**
