### PR TITLE
Update config.js

### PR DESCRIPTION
**Pull request by forkliftcertifiedq2wweftj**
edited some stuff and still, credits to taureon

### CODE REVIEW

**Comment by Taureon** [comment]
you should explain some of these changes, like LEVEL_CAP being changed to 45 trequinquagintillion

**Comment by ClashTest311** [comment]
This is just balance changes... I don't think we need them

**Comment by Zephiii** [comment]
Rejected - No explanation of changes (appear to be unnecessary balance changes) and the changes include some questionable stuff (such as an absurdly large default `LEVEL_CAP`)

**Comment by forkliftcertifiedq2wweftj** [comment]
i set the level cap to 45 trequinquagintillion thinking that it would be the maximum level that you could obtain💀

**Pull request closed without merging**
