### PR TITLE
Fix bad practice

### PR DESCRIPTION
**Pull request by hussainabidi1**
i also accidentally formatted it

### CODE REVIEW

**Comment by Taureon** [comment]
> i also accidentally formatted it

dw about it, you can still unformat it while its not merged yet

**Comment by hussainabidi1** [comment]
uh
are you serious?
also how

**Comment by hussainabidi1** [comment]
I think i fixed the merge conflicts to @Taureon pls merge

**Comment by idkwhattoget** [comment]
lol will this ever get merged

**Comment by Taureon** [comment]
i was waiting for them to unformat it but then i eventually forgor

**Comment by hussainabidi1** [comment]
> i was waiting for them to unformat it but then i eventually forgor

BRUV HOW AM I SUPPOSED TO UNFORMAT 

lol ill try

**Comment by hussainabidi1** [comment]
image

**Comment by Taureon** [comment]
yes

**Pull request merged**
